#!/usr/bin/env node
// Print (or generate) the Battlestation access token from the terminal — the
// non-DMG way to get the token you paste into the phone's Connect screen.
//
//   npm run token          → print the current token, or mint+persist one if none
//   npm run token -- --new → force a fresh token (rotates; old devices must re-pair)
//
// Mirrors electron/main.cjs ensureToken(): same precedence (real env var wins,
// then the persisted env file), same file location + 0600 perms, same strong
// crypto.randomBytes(18).base64url. So a token minted here is identical to what
// the DMG would auto-create, and the running server (which reads the same files)
// will accept it.

const os = require("node:os");
const path = require("node:path");
const fs = require("node:fs");
const crypto = require("node:crypto");

function userConfigDir() {
  if (process.platform === "win32" && process.env.APPDATA) {
    return path.join(process.env.APPDATA, "locals-only");
  }
  if (process.platform === "darwin") {
    return path.join(os.homedir(), "Library", "Application Support", "locals-only");
  }
  const xdg = process.env.XDG_CONFIG_HOME;
  return path.join(xdg || path.join(os.homedir(), ".config"), "locals-only");
}

function parseEnvFile(file) {
  const out = {};
  let raw;
  try {
    raw = fs.readFileSync(file, "utf8");
  } catch {
    return out;
  }
  for (const line of raw.split(/\r?\n/)) {
    const s = line.trim();
    if (!s || s.startsWith("#")) continue;
    const eq = s.indexOf("=");
    if (eq < 1) continue;
    const k = s.slice(0, eq).trim();
    let v = s.slice(eq + 1).trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1);
    }
    out[k] = v;
  }
  return out;
}

// Env files in precedence order (last wins for the running server's view):
// the persisted config-dir file, then the repo's .env.local for dev.
function envFiles() {
  return [
    path.join(userConfigDir(), "battlestation.env"),
    path.join(__dirname, "..", ".env.local"),
  ];
}

function currentToken() {
  if ((process.env.BATTLESTATION_TOKEN || "").trim()) {
    return { token: process.env.BATTLESTATION_TOKEN.trim(), source: "process.env" };
  }
  for (const f of envFiles()) {
    const v = (parseEnvFile(f).BATTLESTATION_TOKEN || "").trim();
    if (v) return { token: v, source: f };
  }
  return null;
}

function persist(token) {
  // Write to the same config-dir file the DMG uses, 0600, append-safe.
  const dir = userConfigDir();
  const file = path.join(dir, "battlestation.env");
  fs.mkdirSync(dir, { recursive: true });
  let prior = "";
  try {
    prior = fs.readFileSync(file, "utf8");
  } catch {
    /* new file */
  }
  // Drop any existing BATTLESTATION_TOKEN line so --new truly rotates.
  const kept = prior
    .split(/\r?\n/)
    .filter((l) => !l.trim().startsWith("BATTLESTATION_TOKEN="))
    .join("\n")
    .replace(/\n+$/, "");
  const sep = kept ? "\n" : "";
  const body =
    kept +
    `${sep}# Battlestation API token (generated by \`npm run token\`). Paste into the\n` +
    `# phone's Connect screen to pair. Delete this line to regenerate.\n` +
    `BATTLESTATION_TOKEN=${token}\n`;
  fs.writeFileSync(file, body, { mode: 0o600 });
  try {
    fs.chmodSync(file, 0o600);
  } catch {
    /* best effort on win32 */
  }
  return file;
}

const forceNew = process.argv.includes("--new");
const existing = currentToken();

if (existing && !forceNew) {
  console.log(existing.token);
  console.error(`\n  ↑ current token (from ${existing.source})`);
  console.error("  Paste it into the phone's Connect screen. Use --new to rotate.");
} else {
  const token = crypto.randomBytes(18).toString("base64url");
  const file = persist(token);
  console.log(token);
  console.error(`\n  ↑ ${forceNew && existing ? "new" : "generated"} token — saved to ${file} (0600)`);
  console.error("  Restart the Battlestation server so it picks up the new token, then");
  console.error("  paste it into the phone's Connect screen.");
}
